### ISSUE TITLE
MatOpt example jupyter notebooks' output error

### ISSUE THREAD

**Issue by xiangyuy** [IDAES/examples-pse#53] opened 2021-07-28 16:46 UTC
Hi, we have noticed that there are errors in the outputs of MatOpt example notebooks. For example, in the output below In[11] in https://idaes.github.io/examples-pse/latest/Examples/MatOpt/monometallic_nanocluster_design_doc.html, it says that the size of the model exceeds the community version's CPLEX' limitation. However, in the source file https://github.com/IDAES/examples-pse/blob/main/src/Examples/MatOpt/monometallic_nanocluster_design.ipynb, the same version of community CPLEX solves the problem successfully and shows no error in the output. Does the website-generation mechanism ignores the original output and tries to generate new outputs on the fly? If so, is it possible that previous version notebooks were used? If the issue arises from CPLEX further reducing the size limitation, we could modify the source files to reduce the size of the examples further or to use NEOS-CPLEX (if the website-generation mechanism supports internet access). Thank you.

**Comment by ksbeattie** [comment] 2021-07-28 18:23
We do re-run all the notebooks when we cut a release.  We do this because not all notebooks are checked-in with results in them and to ensure things are working correctly, which clearly we are missing in this case.

One thing I noticed in just visually comparing the two notebooks pointed to in the issue is that they look like different problem sizes.  I'm not that familiar with CPLEX but the published one has "Variables : 1920" and the checked-in one has "Variables : 426".  Another difference is that XYs looks to have been run on Windows whereas we run our on Linux - hopefully that doesn't matter, but I suppose it could.

I'll dig more to see if I can find when and how the difference in problem size got introduced.  Let me know if you have any ideas on it.

**Comment by lbianchi-lbl** [comment] 2021-07-28 18:37
I looked into the history of the notebook and I found a commit which seems to be related to the increase in problem size (as reported by the `Variables: ` line in the CPLEX output: https://github.com/IDAES/examples-pse/commit/e5e27bb80eb127a8973b9d27d2fc60d21bb54995#diff-b36be862be9825ffc2a9975f11846b599a5aca48fb991afce84ef3041af515df

**Comment by lbianchi-lbl** [comment] 2021-07-29 00:07
@xiangyuy: @ksbeattie and I are working on a way to address this issue. As you correctly assumed, the HTML version of the examples documentation (i.e. the one that's accessible at `https://idaes.github.io/examples-pse`) is generated each time a release of `examples-pse` is cut, by (simplifying) running each notebook using `nbconvert` and then converting the re-run notebook to an HTML page using Sphinx.

We tried to re-run the notebook but we weren't able to have it run without errors. So, in the interest of rapidly deploying a fix to the published website, we think the best way would be to have you do the following:

- Run the `examples-pse` build script on your system
- Verify that the generated HTML looks as it should
- Send us the generated HTML directory as a zipfile
- We can then push the generated HTML directly to the `idaes.github.io` website

To facilitate the process for you, I'll open a PR of `examples-pse` with slight modification to the configuration files that you can check out to run the build process.

A few additional questions/clarifications:

- What exactly is the link that you used in the paper to point to the published HTML version of the notebook? If it doesn't point to a particular version, i.e. if it uses `latest`, the link is not a stable reference, as accessing the link will lead to a different version every time an update is pushed to the `idaes.github.io` website. Once we have a working fix in place, it would be strongly recommended to use a link to a fixed version tag (e.g. `1.10.0` in the link to provide a more stable (although technically still not guaranteed to be immutable) reference for the bibliography
- I looked into the `gh-pages` branch of `IDAES/examples-pse`, which corresponds to the HTML content that's accessible through the `idaes.github.io` website, and I found several occurrences of a similar error in the HTML output, including several past versions. We expect that these would all be fixed by you running the build process on your end, but we just wanted to mention this to make sure that you were aware of it

**Comment by xiangyuy** [comment] 2021-07-29 14:32
> @xiangyuy: @ksbeattie and I are working on a way to address this issue. As you correctly assumed, the HTML version of the examples documentation (i.e. the one that's accessible at `https://idaes.github.io/examples-pse`) is generated each time a release of `examples-pse` is cut, by (simplifying) running each notebook using `nbconvert` and then converting the re-run notebook to an HTML page using Sphinx.
> 
> We tried to re-run the notebook but we weren't able to have it run without errors. So, in the interest of rapidly deploying a fix to the published website, we think the best way would be to have you do the following:
> 
> * Run the `examples-pse` build script on your system
> * Verify that the generated HTML looks as it should
> * Send us the generated HTML directory as a zipfile
> * We can then push the generated HTML directly to the `idaes.github.io` website
> 
> To facilitate the process for you, I'll open a PR of `examples-pse` with slight modification to the configuration files that you can check out to run the build process. **EDIT**: #54
> 
> A few additional questions/clarifications:
> 
> * What exactly is the link that you used in the paper to point to the published HTML version of the notebook? If it doesn't point to a particular version, i.e. if it uses `latest`, the link is not a stable reference, as accessing the link will lead to a different version every time an update is pushed to the `idaes.github.io` website. Once we have a working fix in place, it would be strongly recommended to use a link to a fixed version tag (e.g. `1.10.0` in the link to provide a more stable (although technically still not guaranteed to be immutable) reference for the bibliography
> * I looked into the `gh-pages` branch of `IDAES/examples-pse`, which corresponds to the HTML content that's accessible through the `idaes.github.io` website, and I found several occurrences of a similar error in the HTML output, including several past versions. We expect that these would all be fixed by you running the build process on your end, but we just wanted to mention this to make sure that you were aware of it

Thank you for your instructions. I followed them and got the error ```Failed due to error: Pandoc wasn't found```. I then installed ```pandoc``` with ```pip``` in my environment but still got the same error. What do you suggest to resolve this? Thank you.

**Comment by lbianchi-lbl** [comment] 2021-07-29 15:19
@xiangyuy Sorry about that, I forgot to include that step. I believe the `pandoc` package you installed with `pip install` is not the full pandoc executable needed for this build, which instead should be installed on your system using one of the steps described here: https://pandoc.org/installing.html. 

I've updated the instructions in #54 accordingly, let me know if that works.

**Comment by xiangyuy** [comment] 2021-07-29 20:11
> @xiangyuy Sorry about that, I forgot to include that step. I believe the `pandoc` package you installed with `pip install` is not the full pandoc executable needed for this build, which instead should be installed on your system using one of the steps described here: https://pandoc.org/installing.html.
> 
> I've updated the instructions in #54 accordingly, let me know if that works.

Thanks, it works, and we have generated the correct HTML files. Note that we have updated our CPLEX installations on our computers, so we were not using the same version of CPLEX as before. But those HTML files should serve well as a temporary solution.

**Comment by lbianchi-lbl** [comment] 2021-08-12 18:50
This particular issue was addressed by #55 and is now solved. When cutting the August release, we should make sure this issue doesn't occur again.

**Closed by lbianchi-lbl** 2021-08-12 18:50 UTC
Labels: Priority:High
