### ISSUE TITLE
Solver error on CentOS 8 in Examples/Advanced/CustomProperties/air_separation_case_study.ipynb: ValueError: Cannot load a SolverResults object with bad status

### ISSUE THREAD

**Issue by lbianchi-lbl** [IDAES/examples-pse#77] opened 2021-12-01 00:45 UTC
```txt
2021-11-30 16:37:22,826 INFO - [Worker 0] Convert notebook name=/home/lbianchi/idaes/examples-pse/src/Examples/Advanced/CustomProperties/air_separation_case_study.ipynb: begin
2021-11-30 16:37:22,826 INFO - [Worker 0] Converting: air_separation_case_study.ipynb
2021-11-30 16:37:23,516 INFO - [Worker 0] Stripped tags from: air_separation_case_study.ipynb
2021-11-30 16:37:23,516 INFO - [Worker 0] Running notebook: air_separation_case_study.ipynb
2021-11-30 16:40:27,235 ERROR - [Worker 0] Notebook execution failed: execution error for '/tmp/tmpb256ax7o/air_separation_case_study.ipynb': An error occurred while executing the following cell:
------------------
m1.fs.F101.heat_duty[0].unfix()
m1.fs.F101.vap_outlet.temperature.fix(77.01)

m1.fs.M101.initialize(outlvl=idaeslog.INFO_LOW) 
propagate_state(m1.fs.s01)
m1.fs.F101.initialize(outlvl=idaeslog.INFO_LOW) 
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_116262/2523001707.py in <module>
      2 m1.fs.F101.vap_outlet.temperature.fix(77.01)
      3 
----> 4 m1.fs.M101.initialize(outlvl=idaeslog.INFO_LOW)
      5 propagate_state(m1.fs.s01)
      6 m1.fs.F101.initialize(outlvl=idaeslog.INFO_LOW)

~/opt/conda/envs/build-idaes-1.12.0rc0/lib/python3.8/site-packages/idaes/generic_models/unit_models/mixer.py in initialize(blk, outlvl, optarg, solver, hold_state)
    935             else:
    936                 with idaeslog.solver_log(solve_log, idaeslog.DEBUG) as slc:
--> 937                     res = opt.solve(blk, tee=slc.tee)
    938 
    939             init_log.info(

~/opt/conda/envs/build-idaes-1.12.0rc0/lib/python3.8/site-packages/pyomo/opt/base/solvers.py in solve(self, *args, **kwds)
    624                 else:
    625                     if self._load_solutions:
--> 626                         _model.solutions.load_from(
    627                             result,
    628                             select=self._select_index,

~/opt/conda/envs/build-idaes-1.12.0rc0/lib/python3.8/site-packages/pyomo/core/base/PyomoModel.py in load_from(self, results, allow_consistent_values_for_fixed_vars, comparison_tolerance_for_fixed_vars, ignore_invalid_labels, id, delete_symbol_map, clear, default_variable_value, select, ignore_fixed_vars)
    222                     "an 'aborted' status, but containing a solution")
    223             else:
--> 224                 raise ValueError("Cannot load a SolverResults object "
    225                                  "with bad status: %s"
    226                                  % str(results.solver.status))

ValueError: Cannot load a SolverResults object with bad status: error
ValueError: Cannot load a SolverResults object with bad status: error

2021-11-30 16:40:27,235 ERROR - [Worker 0] Execution failed: generating partial output for '/home/lbianchi/idaes/examples-pse/src/Examples/Advanced/CustomProperties/air_separation_case_study.ipynb'
2021-11-30 16:40:27,235 INFO - [Worker 0] Convert notebook name=/home/lbianchi/idaes/examples-pse/src/Examples/Advanced/CustomProperties/air_separation_case_study.ipynb: end, ok=False duration=184.4s
```

**Comment by andrewlee94** [comment] 2021-12-01 14:01
@lbianchi-lbl Do we know what change/commit caused this to start failing? Solver failures can be really difficult to debug, so it would help if we knew what change had triggered this. Also, did we detect this as soon as it occurred, or does this indicate that there is a gap in our CI testing?

**Comment by andrewlee94** [comment] 2021-12-01 16:42
@lbianchi-lbl So this problem doesn't appear to be a solver availability issue - the solver was called but failed. It might be due to the linear sub-solver that was available, but I would have expected this to use the IDAES IPOPT so I would have expected the same result.

**Comment by lbianchi-lbl** [comment] 2021-12-02 03:05
@andrewlee94 I tried running the notebook manually (i.e. start a Jupyter server with `jupyter notebook` and then opening the `Examples/Advanced/CustomProperties/air_separation_case_study` notebook) in the same environment:

- Running the notebook from scratch results in the same error
- After splitting the cell where the error occurs (the second in section 7.6, should be 35) in multiple cell with one line each, the problematic line seems to be:
  
  ```py
  m1.fs.M101.initialize(outlvl=idaeslog.INFO_LOW)
  ```
- After changing the `outlvl` to `idaeslog.DEBUG`, the result is the following: [cell-output-error.log](https://github.com/IDAES/examples-pse/files/7638631/cell-output-error.log)
- Re-running the cell without restating the output seems to work (the output is 
[cell-output-no-error.log](https://github.com/IDAES/examples-pse/files/7638681/cell-output-no-error.log))
- In case it might be useful for someone, I used `jq` to extract the cell output from the notebook file:
  ```sh
  jq < examples-pse-77-no-error.ipynb '.cells[] | select(.execution_count == 36).outputs[0].text[]' --raw-output > cell-output-no-error.log
  ```

**Comment by agarciadiego** [comment] 2021-12-02 17:31
@andrewlee94 Yes I'll give it a look.

**Comment by ksbeattie** [comment] 2021-12-09 19:23
> @andrewlee94 Yes I'll give it a look.

Any news?  We are planning on cutting the final "November" release early next week.

**Comment by agarciadiego** [comment] 2021-12-10 16:13
@ksbeattie I've ran the notebook a couple of times and I can't seem to reproduce the error

**Comment by ksbeattie** [comment] 2021-12-16 19:38
@agarciadiego, perhaps we can get the 3 of us together to try and get to the bottom of what is happening here.  That being that it works for you, but doesn't for us on our build system.

**Comment by agarciadiego** [comment] 2021-12-20 16:43
@ksbeattie sure sounds like a good idea

**Comment by lbianchi-lbl** [comment] 2021-12-22 23:03
As mentioned in #83, I tried to build the notebook on two different Linux OSes:

- CentOS 8 (which is the same OS we have on our build system)
- Ubuntu 20.04 (newer version of Ubuntu, used in the GitHub Actions runners, where the notebook runs fine)

To reduce confounding factors I used two Docker containers running on the same hosts, starting from the respective default OS image, and with setup steps as similar as possible.

The notebook fails on CentOS with the same error described above, and works fine on Ubuntu, which seems to suggest this might be an OS-dependent issue, possibly introduced with a recent Ipopt update/build (since the notebook worked fine on the same system as of the Aug release). @eslickj @jsiirola, what are your thoughts on this?

For reference, these are the steps I used for CentOS:

```
yum install -y wget git lapack blas libgfortran libgomp
wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda
export PATH=/opt/conda/bin:$PATH
conda init bash && exec bash
exec bash
conda create -c conda-forge -y -n idaes-pse python=3.8 pandoc && conda activate idaes-pse
git clone https://github.com/IDAES/examples-pse && cd examples-pse
pip install -r requirements.txt
idaes get-extensions --verbose
python build.py -v -x
python build.py -v -cdr -w 1
```

**Comment by eslickj** [comment] 2021-12-27 04:49
I just noticed this issue.  Since I’ve been testing solvers in multiple Linux distros for a while, I’d say this is a pretty common problem.  If the problem is badly scaled or somehow sort-of on the bubble, small differences in the system libraries may cause the problem not to solve on some random OS.  The usually solution is to improve scaling or problem formulation.  The bad solver status error often comes from something just not solving.

**Comment by adowling2** [comment] 2021-12-27 14:30
I suspect this is because there are slight differences in the numeric libraries across OS versions. Hypothesis: This goes unnoticed for most optimization problems, but becomes an issue with poor scaling. With poor scaling, the underlying linear systems are ill conditioned and slight differences in the linear solvers (and dependencies) causes big differences in the calculated steps.

**Comment by jsiirola** [comment] 2022-01-04 15:58
I believe that our builds of ipopt dynamically link against the system blas and lapack on linux, so I would tend to agree with @adowling2.

**Comment by adowling2** [comment] 2022-01-04 17:07
Years ago, I would get different answers on Windows and Linux using the same version of GAMS. GAMS ships with all of the solvers compiled. I suspected slightly different versions of the libraries were being used and the problem was poorly scaled.

**Comment by ksbeattie** [comment] 2022-01-06 19:34
Closing this, because this particular notebook is working ok, but we will improve the CI so other notebooks, which might need to have this formulation improved will be found.

**Closed by ksbeattie** 2022-01-06 19:34 UTC
Labels: Priority:High
